name: vortex_cli
description: "Official CLI for VORTEX™ framework to build Flutter and Server
  Applications easily."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ansicolor: ">=2.0.3 <3.0.0"
  collection: ">=1.19.0 <2.0.0"
  dart_style: ">=2.3.6 <3.0.0"
  dcli: ">=6.0.5 <7.0.0"
  http: ">=1.2.2 <2.0.0"
  intl: ">=0.19.0 <1.0.0"
  meta: ">=1.15.0 <2.0.0"
  path: ">=1.9.0  <2.0.0"
  process_run: ">=1.1.0 <2.0.0"
  pubspec_parse: ">=1.3.0 <2.0.0"
  pub_semver: ">=2.1.4 <3.0.0"
  recase: ">=4.1.0 <5.0.0"
  version: ">=3.0.2 <4.0.0"
  yaml: ">=3.1.2 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
