name: vortex_cli
description: "Official CLI for VORTEX™ framework to build Flutter and Server
  Applications easily."
version: 0.0.3+10
repository: https://github.com/vortex-flutter/vortex_cli/tree/main
issue_tracker: https://github.com/vortex-flutter/vortex_cli/issues
homepage: https://vortex.brighthustle.in
documentation: https://vortex.brighthustle.in/getting-started
topics: [vortex, nuxt, flutter, build-system]
funding: [https://github.com/sponsors/vortex-flutter]

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ansicolor: ">=2.0.3 <3.0.0"
  collection: ">=1.19.0 <2.0.0"
  dart_style: ">=2.3.6 <3.0.0"
  dcli: ">=6.0.5 <7.0.0"
  http: ">=1.2.2 <2.0.0"
  intl: ">=0.19.0 <1.0.0"
  meta: ">=1.15.0 <2.0.0"
  path: ">=1.9.0  <2.0.0"
  process_run: ">=1.1.0 <2.0.0"
  pubspec_parse: ">=1.3.0 <2.0.0"
  pub_semver: ">=2.1.4 <3.0.0"
  recase: ">=4.1.0 <5.0.0"
  version: ">=3.0.2 <4.0.0"
  yaml: ">=3.1.2 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

executables:
  vortex: vortex
  vortex_cli: vortex
